The default value of UpdateInterval is different in Windows Server 2…
MicrosoftDocs/windowsserverdocs pull request #4019
Opened 2020-03-15 12:30 UTC by taka-oi

…016.

2020-03-17 20:34 UTC, eross-msft commented
@dcuomo  Please review this change and let me know if it's ready to merge for publishing. Thanks!

2020-04-10 16:58 UTC, eross-msft commented
Sending this question to PM. Will respond after I get response.

2020-11-26 20:08 UTC, illfated commented
@eross-msft : Do you think it would be OK to ask the PM again, just to see if we can have this confirmed before WS 2016 goes out of mainstream support?

2020-11-26 20:10 UTC, illfated commented
@taka-oi : Would you be able to resolve the file conflict, just in case we get a positive feedback for this change?

2020-11-30 19:05 UTC, eross-msft commented
@illfated The PM apparently isn't on GitHub. I will email him with this again and see if we can get this resolved.

2020-12-29 15:02 UTC, illfated commented
@taka-oi : Any chance you will be returning to this Pull Request to resolve the file conflict, to make it available for merging? (I assume that there will be a reply from the MS Docs team confirming the validity of this contribution, I just don't know when.)

2020-12-29 15:20 UTC, illfated commented
Anyway, if you find that the document changes, since you opened this PR, are causing too much trouble for you, it should be quite easy to close this PR and open a new PR containing the same change.

2021-01-20 16:29 UTC, PRMerger13 commented
@taka-oi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-01-20 17:39 UTC, illfated commented
I have tried a few times to use search engines to see if I could locate more information about the specific details regarding Windows Server 2016 and `W32Time\Config\\UpdateInterval = 100`, but I have not been successful yet. If there exists any information supporting this statement out there, it would be quite helpful to link it here in a new comment, or in the main PR comment.

2021-01-21 18:56 UTC, Teresa-Motiv requested changes
Please clarify: Is the default value

2021-01-21 18:56 UTC, Teresa-Motiv commented on WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md
> +|**UpdateInterval** |All versions |Specifies the number of clock ticks between phase correction adjustments. The default value for domain controllers is **100**. The default value for domain members
Please clarify what you mean by "in any state." It should only be bold if it's part of the actual value. 
Does it mean that for Windows Server 2016, the default value is *100* whether the server is a domain controller, a domain member, or a standalone server?"

2021-01-21 19:14 UTC, Teresa-Motiv commented
@illfated were you able to confirm the default value?

2021-01-22 00:13 UTC, illfated commented
Sorry, I have not found this value documented elsewhere, even though I wish I had found something that would clarify this issue. I may not have been diligent enough with my searches.

2021-04-02 16:39 UTC, Teresa-Motiv commented
Reassigning this PR--the article is currently being rewritten by another team, and that may resolve this issue.

2021-04-02 23:43 UTC, illfated commented
#please-close

2021-04-02 23:43 UTC, closed without merging