Add note about additional config for ClassicCompute VMs
MicrosoftDocs/windowsserverdocs pull request #4603
Opened 2020-06-30 14:35 UTC by andreiztm

2020-06-30 22:07 UTC, illfated commented
#sign-off

2020-08-27 17:39 UTC, andreiztm commented
Hi, could someone please review and merge this? Thanks, Andrei.

2020-08-27 17:57 UTC, illfated commented
@eross-msft : Would you be available to follow up on this PR, or do we need to check with someone else?

2020-08-27 18:19 UTC, eross-msft commented on WindowsServerDocs/get-started/extended-security-updates.md
> +> Microsoft.ClassicCompute type VMs require additional configuration for ESU deployment, as they do not have access to the Azure Resource Manager, in particular the [Azure Instance Metadata Service](
@andreiztm  Please change the following: 
- ESU to Extended Security Updates. For some reason, even though we show the acronym, it's always spelled out completely in the text.
- "Do not have" to "don't have"

I'm unclear whether your are a Microsoft employee and subject matter expert on this, or if we need to have someone review this text before publishing. Can you clarify your role? Thanks!

2020-08-27 19:13 UTC, andreiztm commented
@eross-msft thank you for the suggestions, I added them in (hopefully correct) and sent you an e-mail confirming my role.

2020-08-27 19:23 UTC, eross-msft commented on WindowsServerDocs/get-started/extended-security-updates.md
> +> Microsoft.ClassicCompute type VMs require additional configuration for Extended Security Updates deployment, as they don't have access to the Azure Resource Manager, in particular the [Azure Instan
@andreiztm  After looking at this a bit more, when we spell out ESU it gets a bit long. I would suggest chopping it down slightly. What do you think about: 
"Microsoft.ClassicCompute VMs require additional configuration for Extended Security Updates deployment, as they don't have access to the [Azure Instance Metadata Service](https://docs.microsoft.com/azure/virtual-machines/windows/instance-metadata-service), which determines your Extended Security Updates eligibility. Please contact [Microsoft support](http://support.microsoft.com/contactus?PID=17336) for more help."

2020-08-27 19:35 UTC, andreiztm commented
@eross-msft thank you very much for the ongoing feedback, learning a lot. I added the latest changes.

2020-08-27 19:40 UTC, illfated approved these changes
Looks very good to me.

2020-08-27 19:40 UTC, illfated commented
#sign-off

2020-08-27 19:41 UTC, illfated commented on WindowsServerDocs/get-started/extended-security-updates.md
> +> Microsoft.ClassicCompute VMs require additional configuration for Extended Security Updates deployment, as they don't have access to the [Azure Instance Metadata Service](https://docs.microsoft.com
Ouch. I overlooked a typo:
```suggestion
> Microsoft.ClassicCompute VMs require additional configuration for Extended Security Updates deployment, as they don't have access to the [Azure Instance Metadata Service](https://docs.microsoft.com/azure/virtual-machines/windows/instance-metadata-service), which determines Extended Security Updates eligibility. Please contact [Microsoft support](http://support.microsoft.com/contactus?PID=17336) for more help.
```

2020-08-27 19:41 UTC, illfated requested changes
Please add the typo correction, if you still can.

2020-08-27 19:56 UTC, andreiztm commented
Good eyes :D I read it like 5 times and still missed it, alas.. :P

2020-08-27 19:57 UTC, eross-msft commented
Thank you both! I'll go ahead and merge this

2020-08-27 19:57 UTC, merged