Update capacity-planning-for-active-directory-domain-services.md
MicrosoftDocs/windowsserverdocs pull request #5402
Opened 2021-03-25 12:36 UTC by kenbrumf

Clarified storage performance considerations for more complex scenarios.

2021-03-25 12:36 UTC, PRMerger15 commented
@kenbrumf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-03-25 13:12 UTC, PRMerger8 commented
@kenbrumf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-03-25 21:11 UTC, Teresa-Motiv approved these changes

2021-03-25 21:11 UTC, Teresa-Motiv commented
#sign-off

2021-03-26 06:41 UTC, illfated commented on WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md
> +Specifically, shared storage (RAID, SAN, NAS, JBOD (i.e. Storage Spaces), VHD) all have the ability to be oversubscribed/overloaded by other work loads that are placed on the back end storage.  They
```suggestion
Specifically, shared storage (RAID, SAN, NAS, JBOD (i.e. Storage Spaces), VHD) all have the ability to be oversubscribed/overloaded by other work loads that are placed on the back end storage.  They also add in the challenge that SAN/network/driver issues (everything between the physical disk and the AD application) can cause throttling and/or delays. For clarification, these are not “bad” configurations, they are more complex configurations that require every component along the way to be working properly, thus requiring additional attention to ensure that performance is acceptable.  See Appendix C, subsection "Introducing SANs", and Appendix D later in this document for more detailed explanations. Also, whereas Solid State Drives do not have the limitation of spinning disks (Hard Drives) regarding only allowing 1 IO at a time to be processed, they do still have IO limitations, and overloading/oversubscribing of SSDs is possible.  In short, the end goal of all storage performance efforts, regardless of underlying storage architecture and design, is to ensure the needed amount of Input/output Operations Per Second (IOPS) are available and that those IOPS happen within an acceptable time frame (as specified elsewhere in this document). For those scenarios with locally attached storage, reference the Appendix C for the basics in how to design traditional local storage scenarios. These principals are generally applicable to more complex storage tiers and will also help in dialog with the vendors supporting backend storage solutions.
```
Some adjustments for grammar, punctuation, and readability.

2021-03-26 22:00 UTC, PRMerger6 commented
@kenbrumf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-03-26 22:45 UTC, Teresa-Motiv requested changes
subsection "Introducing SANs",
   The comma should be inside the quote marks.

allowing 1 IO at a time
    Spell out "one"

2021-03-26 23:04 UTC, PRMerger6 commented
@kenbrumf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-03-27 10:16 UTC, illfated commented on WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md
> +Specifically, shared storage (RAID, SAN, NAS, JBOD (i.e. Storage Spaces), VHD) all have the ability to be oversubscribed/overloaded by other work loads that are placed on the back end storage.  They
I missed out on one extra set of quotation marks to change from curly quotes to straight quotes (these are not “bad” configurations):
```suggestion
Specifically, shared storage (RAID, SAN, NAS, JBOD (i.e. Storage Spaces), VHD) all have the ability to be oversubscribed/overloaded by other work loads that are placed on the back end storage. They also add in the challenge that SAN/network/driver issues (everything between the physical disk and the AD application) can cause throttling and/or delays. For clarification, these are not "bad" configurations, they are more complex configurations that require every component along the way to be working properly, thus requiring additional attention to ensure that performance is acceptable.  See Appendix C, subsection "Introducing SANs," and Appendix D later in this document for more detailed explanations. Also, whereas Solid State Drives do not have the limitation of spinning disks (Hard Drives) regarding only allowing one IO at a time to be processed, they do still have IO limitations, and overloading/oversubscribing of SSDs is possible. In short, the end goal of all storage performance efforts, regardless of underlying storage architecture and design, is to ensure that the needed amount of Input/output Operations Per Second (IOPS) is available and that those IOPS happen within an acceptable time frame (as specified elsewhere in this document). For those scenarios with locally attached storage, reference Appendix C for the basics in how to design traditional local storage scenarios. These principals are generally applicable to more complex storage tiers and will also help in dialog with the vendors supporting backend storage solutions.
```
Simplified a couple of extra double spaces between sentences. Simplified "reference the Appendix C" by removing the definite article "the", in compliance with its most common expression usage. Also: "to ensure that the needed amount" — "is available" (amount/singular).

2021-03-29 13:35 UTC, PRMerger15 commented
@kenbrumf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-03-29 16:12 UTC, illfated approved these changes
Looks good to me, I am happy with this result.

2021-03-29 16:13 UTC, illfated commented
#sign-off

2021-03-29 16:13 UTC, PRMerger9 commented
@illfated: I'm sorry - only the author of this article, @teresa-motiv, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-03-29 16:13 UTC, illfated commented
Yes, I know. My sign-off comment is based on an agreement with the MS Docs team.

2021-03-29 16:35 UTC, Teresa-Motiv commented
#Sign-off

2021-04-05 16:06 UTC, Teresa-Motiv approved these changes

2021-04-05 16:07 UTC, Teresa-Motiv commented
#label:"sign-off"

2021-04-12 16:10 UTC, Teresa-Motiv commented
@JasonGerend Can you merge this PR, or do you know who can?

Thanks

2021-05-10 18:34 UTC, Teresa-Motiv commented
#sign-off

2021-05-10 19:12 UTC, illfated commented
@denisebmsft : Would you be able to merge this PR? I mean, it has been verified by the assigned author, who don't have merging rights, though I don't know who is the correct person to perform the merge.

2021-06-30 17:47 UTC, merged