Update vpn-deploy-ras.md
MicrosoftDocs/windowsserverdocs pull request #5768
Opened 2021-08-03 06:43 UTC by cstraessner

adding recommendation on  IPv4 subnet assignment

2021-08-03 06:43 UTC, PRMerger16 commented
@cstraessner : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-17 21:45 UTC, Teresa-Motiv requested changes

2021-09-17 21:45 UTC, Teresa-Motiv commented on WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md
> +>[!NOTE] for optimal network performance, The VPN Server  itself  should not  have  a network interface in the IPv4 subnet  where the Clients  are assigned  IPv4 addresses from.
Needs revisions:
    > [!NOTE]  
    > For optimal network performance, the VPN server itself should not have a network interface in the same IPv4 subnet that assigns IPv4 addresses to the clients.  If the VPN server does have a network interface in that subnet, a broadcast or multicast that is sent to that subnet could cause a latency spike.

2021-11-16 01:35 UTC, IngridAtMicrosoft commented
Teresa's suggested changes were added to a different PR, see comment above.

2021-11-16 01:35 UTC, closed without merging