Updating example script text
MicrosoftDocs/windowsserverdocs pull request #5776
Opened 2021-08-05 04:38 UTC by pamcdo

The text relating to the example .inf file suggested that users look in an Appendix that doesn't exist. I modified the text to say that the example was below in the article and provided a link to the section.

2021-08-05 04:38 UTC, PRMerger17 commented
@pamcdo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-05 15:49 UTC, Teresa-Motiv requested changes
Please use "later in this article" instead of "below" to meet MS style guidelines. Other changes OK.

2021-08-07 02:32 UTC, PRMerger14 commented
@pamcdo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-09 16:03 UTC, Teresa-Motiv approved these changes

2021-08-09 16:04 UTC, Teresa-Motiv commented
#sign-off

2021-11-16 01:36 UTC, IngridAtMicrosoft commented
Addressed.

2021-11-16 01:36 UTC, closed without merging