Update pktmon-wac-extension.md
MicrosoftDocs/windowsserverdocs pull request #6517
Opened 2022-06-08 07:31 UTC by itamar56

There is a mistake in the server version, the document says: "To use the tool, the target server needs to be running Windows Server 2019 version 1903 (19H1) and above." This version doesn't exist. It should be Windows Server, Version 1903

2022-06-08 07:31 UTC, PRMerger3 commented
@itamar56 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-13 05:57 UTC, itamar56 commented
Hi team, Kind reminder.
@khdownie

2022-08-15 15:14 UTC, khdownie requested changes

2022-08-15 15:14 UTC, khdownie commented on WindowsServerDocs/networking/technologies/pktmon/pktmon-wac-extension.md
> +- To use the tool, the target server needs to be running Windows Server, version 1903 (Semi-Anual Channel) and above.
```suggestion
- To use the tool, the target server needs to be running Windows Server 2019, version 1903 or later.
```

2022-08-15 20:29 UTC, khdownie approved these changes

2022-08-15 20:29 UTC, khdownie commented
#sign-off

2022-12-05 22:46 UTC, merged