trusted roots article split conceptual + how-to
MicrosoftDocs/windowsserverdocs pull request #6893
Opened 2022-12-05 04:27 UTC by gswashington

2022-12-05 04:29 UTC, opbld32 commented
Learn Build status updates of commit _[0f43382](https://github.com/gswashington/windowsserverdocs/commits/0f43382d44ffd5a711394cf2dbf53f999dbf4e02)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :warning:Warning | | [Details](#user-content-f5259ac18214db1cc84d3c732197963e-41322a01)
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :warning:Warning | | [Details](#user-content-5cd52b78f338e619b86724b272a8f628-41322a01)
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |

<a id="f5259ac18214db1cc84d3c732197963e-41322a01"></a>
### [WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md)
 - **Line 2, Column 1**: **[Warning: ms-topic-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 4, Column 10**: **[Warning: ms-topic-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-topic-invalid?branch=main)]** `````Invalid value for 'ms.topic': ''.`````
 - **Line 25, Column 310**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'configure-trusted-roots-disallowed-certificates'.`````
 - **Line 49, Column 5**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'configure-trusted-roots-disallowed-certificates'.`````
 - **Line 75, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './administration/windows-commands/certutil.md'.`````
 - **Line 6, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'robin.harwood' is not a valid Microsoft alias.`````

<a id="5cd52b78f338e619b86724b272a8f628-41322a01"></a>
### [WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md)
 - **Line 2, Column 1**: **[Warning: ms-topic-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````
 - **Line 4, Column 10**: **[Warning: ms-topic-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-topic-invalid?branch=main)]** `````Invalid value for 'ms.topic': ''.`````
 - **Line 405, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './administration/windows-commands/certutil.md'.`````
 - **Line 6, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'robin.harwood' is not a valid Microsoft alias.`````
 - **Line 328, Column 6**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'style' on tag 'col' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 329, Column 6**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'style' on tag 'col' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 330, Column 6**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'style' on tag 'col' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212050427388639-6893/BuildReport?accessString=f4f653a4ce0912a8e96f574f83020062bc9d1e4d13e29810095de97086c4e348).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 16:32 UTC, Court72 commented
@robinharwood, @Xelu86

Can you review the proposed changes? 

New content should be submitted via the private repo to benefit from staging, validation, and Acrolinx checks. Let us know if you'd like assistance with moving the commits into the private repo.
Note that the new articles must be added to a TOC.

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team
#assign-reviewer: @robinharwood
#assign-reviewer: @Xelu86
#assign: @robinharwood
#assign: @Xelu86

2022-12-05 18:10 UTC, opbld31 commented
Learn Build status updates of commit _[0a16787](https://github.com/gswashington/windowsserverdocs/commits/0a167873415d2bf29b031f658370ce008e3f3502)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :warning:Warning | | [Details](#user-content-727018d986635f40d0a6cbab6d5c6226-93409399)
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :warning:Warning | | [Details](#user-content-f5259ac18214db1cc84d3c732197963e-93409399)
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :warning:Warning | | [Details](#user-content-5cd52b78f338e619b86724b272a8f628-93409399)

<a id="727018d986635f40d0a6cbab6d5c6226-93409399"></a>
### [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 13**: **[Warning: ms-service-subservice-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'windows server active directory certificate services'.`````

<a id="f5259ac18214db1cc84d3c732197963e-93409399"></a>
### [WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 13**: **[Warning: ms-service-subservice-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'windows server active directory certificate services'.`````
 - **Line 25, Column 310**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'configure-trusted-roots-disallowed-certificates'.`````
 - **Line 49, Column 5**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'configure-trusted-roots-disallowed-certificates'.`````
 - **Line 75, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './administration/windows-commands/certutil.md'.`````
 - **Line 6, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'robin.harwood' is not a valid Microsoft alias.`````

<a id="5cd52b78f338e619b86724b272a8f628-93409399"></a>
### [WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 13**: **[Warning: ms-service-subservice-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)]** `````Invalid value for 'ms.service': 'windows server active directory certificate services'.`````
 - **Line 382, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './administration/windows-commands/certutil.md'.`````
 - **Line 7, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'robin.harwood' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212051809138588-6893/BuildReport?accessString=1d2e2134e10aa2a1cae5aab843d8489aaa252b6847b1d2d522fb60b68b2f1abb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 18:19 UTC, opbld33 commented
Learn Build status updates of commit _[040b86d](https://github.com/gswashington/windowsserverdocs/commits/040b86dea8f04a4290ab3a1612f2fd7e086318b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :warning:Warning | | [Details](#user-content-f5259ac18214db1cc84d3c732197963e-f0bf58e5)
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :warning:Warning | | [Details](#user-content-5cd52b78f338e619b86724b272a8f628-f0bf58e5)
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |

<a id="f5259ac18214db1cc84d3c732197963e-f0bf58e5"></a>
### [WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md)
 - **Line 75, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../administration/windows-commands/certutil.md'.`````
 - **Line 6, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'robin.harwood' is not a valid Microsoft alias.`````

<a id="5cd52b78f338e619b86724b272a8f628-f0bf58e5"></a>
### [WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md)
 - **Line 382, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../administration/windows-commands/certutil.md'.`````
 - **Line 7, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.learn.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'robin.harwood' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212051816519065-6893/BuildReport?accessString=a28072f862382aab22c07947a24ea25d1bc6831689f7e8b495c67e9f27e452a2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 20:54 UTC, opbld33 commented
Learn Build status updates of commit _[9da42c9](https://github.com/gswashington/windowsserverdocs/commits/9da42c96ad7f74f4a137dcf10697d8b36c823ec2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212052052011032-6893/BuildReport?accessString=7845cfbd5f4dc20b62ca6b7012597eae1a3fb5024288c2ce208815a127fe0774).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 19:43 UTC, opbld31 commented
Learn Build status updates of commit _[1a2dbb4](https://github.com/gswashington/windowsserverdocs/commits/1a2dbb4b96892ef36af101de53f6c7d8ca63aa5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :warning:Warning | | [Details](#user-content-727018d986635f40d0a6cbab6d5c6226-96578d04)
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :warning:Warning | | [Details](#user-content-5cd52b78f338e619b86724b272a8f628-96578d04)
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :white_check_mark:Succeeded | |

<a id="727018d986635f40d0a6cbab6d5c6226-96578d04"></a>
### [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md)
 - **Line 2064, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'configure-trusted-roots-disallowed-certificates.md'.`````

<a id="5cd52b78f338e619b86724b272a8f628-96578d04"></a>
### [WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md)
 - **Line 347, Column 3**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212071940492648-6893/BuildReport?accessString=0f11f87b734008244c0331d8b6948b533c3f3cb43a099342947d7cdc5c0cc79e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 20:03 UTC, opbld31 commented
Learn Build status updates of commit _[e5719dd](https://github.com/gswashington/windowsserverdocs/commits/e5719dd5d501c4e7fec15c2ee4a689e6f44edb72)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :warning:Warning | | [Details](#user-content-727018d986635f40d0a6cbab6d5c6226-52c0d447)
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :white_check_mark:Succeeded | |

<a id="727018d986635f40d0a6cbab6d5c6226-52c0d447"></a>
### [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md)
 - **Line 2064, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './windows-commands/configure-trusted-roots-disallowed-certificates'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212072002007722-6893/BuildReport?accessString=450e1fb1845d006f2181a27d18bac5dda781a5ea5720e2a766c4f5bb418f79b3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 20:23 UTC, opbld31 commented
Learn Build status updates of commit _[7ca7b18](https://github.com/gswashington/windowsserverdocs/commits/7ca7b185c6a0660fd8917bd82ace801c61d0a8ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212072021149672-6893/BuildReport?accessString=45fd1a9f0b1587b0d584d762b9cacefd4b0e583bd9a5ac2e4e794d0792b24b12).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 22:48 UTC, opbld33 commented
Learn Build status updates of commit _[9884186](https://github.com/gswashington/windowsserverdocs/commits/988418645f74f9bf23e1de9a6c0650c6b770915c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212092246210920-6893/BuildReport?accessString=9981f13ce4f3a430a4e4acc14f03045d969166c8f88f75633fe01c71fa6c02f1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-14 05:17 UTC, opbld32 commented
Learn Build status updates of commit _[1badec6](https://github.com/gswashington/windowsserverdocs/commits/1badec62373fb84d322515fcc21265f9c94b5f4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212140515026961-6893/BuildReport?accessString=e39d5911091ea0750dc9e56beecd1800c88d5ed53f128880ac0630bc636997ee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 00:05 UTC, opbld32 commented
Learn Build status updates of commit _[542a67d](https://github.com/gswashington/windowsserverdocs/commits/542a67d4c452a8fc78a0845a25bbfc79e4271b9f)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :bulb:Suggestion | | [Details](#user-content-f5259ac18214db1cc84d3c732197963e-7e7afcb8)
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :white_check_mark:Succeeded | |

<a id="f5259ac18214db1cc84d3c732197963e-7e7afcb8"></a>
### [WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md)
 - **Line 76, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc734054(v=ws.10)?redirectedfrom=MSDN' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212220004296946-6893/BuildReport?accessString=cf75685fb09cc16a30d4b30c7a209381824aa3a259fa2c232335833e1fd6e8e2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 18:15 UTC, opbld33 commented
Learn Build status updates of commit _[e955434](https://github.com/gswashington/windowsserverdocs/commits/e9554344200822e49be55d1edf3670baaa86e02a)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md) | :bulb:Suggestion | | [Details](#user-content-f5259ac18214db1cc84d3c732197963e-6aaaa7ac)
[WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md) | :bulb:Suggestion | | [Details](#user-content-5cd52b78f338e619b86724b272a8f628-6aaaa7ac)
[WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/administration/windows-commands/certutil.md) | :white_check_mark:Succeeded | |

<a id="f5259ac18214db1cc84d3c732197963e-6aaaa7ac"></a>
### [WindowsServerDocs/identity/ad-cs/certificates-and-trust.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/certificates-and-trust.md)
 - **Line 78, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc734054(v=ws.10)?redirectedfrom=MSDN' will be broken in isolated environments. Replace with a relative link.`````

<a id="5cd52b78f338e619b86724b272a8f628-6aaaa7ac"></a>
### [WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-TRDC/WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md)
 - **Line 37, Column 105**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc734054(v=ws.10)?redirectedfrom=MSDN#turn-off-automatic-root-certificates-update' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202212281813394210-6893/BuildReport?accessString=b729ca1ae4bcbef4ddac5b5ab70a832c0a1454a9222bab8b8a197a4d17d20258).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-18 17:33 UTC, robinharwood commented
Hi @gswashington, just to let you know I'm review this today/tomorrow. Please hold off on any edits until I've posted my feedback.

Thanks,
Robin

2023-01-18 22:33 UTC, robinharwood requested changes
Just a few minor changes 😄 thanks for your hard work on this @gswashington

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +The following automatic update mechanisms are available in Windows Server 2012 R2 and Windows 8.1 and newer Windows versions or when the appropriate software update is installed (for older operating
```suggestion
The following automatic update mechanisms are available in Windows Server and the Windows client when the appropriate software update is installed (for older operating systems discussed in this article):
```

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +Automatic update functionality also can be disabled if necessary, although this isn't recommended. See [Event ID 8 — Automatic Root Certificates Update Configuration](https://learn.microsoft.com/prev
although **this** isn't recommended. - This isn't always clear to the reader when English is their second language or the text is localized. Could you use a noun or rephase?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +Automatic update functionality also can be disabled if necessary, although this isn't recommended. See [Event ID 8 — Automatic Root Certificates Update Configuration](https://learn.microsoft.com/prev
```suggestion
Automatic update functionality also can be disabled if necessary, although this isn't recommended. For more information, see [Event ID 8 — Automatic Root Certificates Update Configuration](https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc734054(v=ws.10)?redirectedfrom=MSDN#turn-off-automatic-root-certificates-update) for more information.
```

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +- Examine the set of root certificates in the Windows Root Certificate Program. This enables administrators to select a subset of certificates to distribute by using a Group Policy Object (GPO). This
Starting the second sentence with this. This isn't always clear to the reader when English is their second language or the text is localized. Could you use a noun or rephase?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +If the computers in your network are configured in a domain environment and they're unable to use the automatic update mechanism or download CTLs, you can implement a GPO in AD DS to configure those
This is quite a complex sentence. Could it be reworded to simplify?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +> The trusted and untrusted CTLs can be updated on a daily basis, so ensure that you keep the files synchronized by using a scheduled task or another method (such as a script that handles error condi
```suggestion
> The trusted and untrusted CTLs can be updated on a daily basis, so ensure that you keep the files synchronized by using a scheduled task or another method (such as a script that handles error conditions) to update the shared folder or web virtual directory. For more information about creating a scheduled task, see [Schedule a Task](https://technet.microsoft.com/library/cc748993.aspx). If you plan to write a script to make daily updates, see the [New Certutil Options]() and [Potential errors with Certutil -SyncWithWU]() sections of this document. These sections provide more information about command options and the error conditions.
```

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +Some organizations may want only the untrusted CTLs (not the trusted CTLs) to be automatically updated. To accomplish this, you can create two .adm templates to add to Group Policy.
`To accomplish this` - This isn't always clear to the reader when English is their second language or the text is localized. Could you use a noun or rephase?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +It may be necessary for various reasons to delete all Trusted and Untrusted CTLs from a client machine. The following Certutil options can be used to accomplish this.
`can be used to accomplish this.` - This isn't always clear to the reader when English is their second language or the text is localized. Could you use a noun or rephase?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/configure-trusted-roots-disallowed-certificates.md
> +- If there's a change in the trusted root certificates, you'll see: "Warning\! Encountered the following no longer trusted roots: \<folder path\>\\\<thumbprint\>.crt. Use "-f -f" options to force the
`Use "-f -f" options to force the delete of the above ".crt" files.` Can we replace or provide more locational information to the word 'above'. I'm not even sure the word above needs to be there?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/certificates-and-trust.md
> +Trusted and untrusted root certificates are contained in a certificate trust list (CTL). When you want to distribute root certificates you use a CTL. Windows Server features automatic daily update fu
```suggestion
Trusted and untrusted root certificates are contained in a certificate trust list (CTL). When you want to distribute root certificates, you use a CTL. Windows Server features automatic daily update functionality that includes downloads of latest CTLs. The list of trusted and untrusted root certificates are called the Trusted CTL and Untrusted CTL, respectively. See [Announcing the automated updater of untrustworthy certificates and keys](https://blogs.technet.com/b/pki/archive/2012/06/12/announcing-the-automated-updater-of-untrustworthy-certificates-and-keys.aspx) for more information.
```

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/certificates-and-trust.md
> +By default, Windows downloads the CTLs from the Internet via an automatic mechanism called the CTL Updater. The public URLs used by the CTL Updater can be made available to clients. These are:
` These are:` - These isn't always clear to the reader when English is their second language or the text is localized. Could you use a noun or rephase?

2023-01-18 22:33 UTC, robinharwood commented on WindowsServerDocs/identity/ad-cs/certificates-and-trust.md
> +Automatic update functionality also can be disabled if necessary, although this isn't recommended.
```suggestion
Automatic update functionality also can be disabled if necessary, although isn't recommended.
```

2023-04-04 17:34 UTC, merged