acrolinx quality improvements: cprofile.md
MicrosoftDocs/windowsserverdocs pull request #6936
Opened 2023-01-03 18:41 UTC by gswashington

2023-01-03 18:50 UTC, opbld33 commented
Learn Build status updates of commit _[27680f2](https://github.com/gswashington/windowsserverdocs/commits/27680f2bbebba5eae20cefe1e2a523bdeeb8795c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/cprofile.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-cprofile.md-acrolinx2/WindowsServerDocs/administration/windows-commands/cprofile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202301031841074399-6936/BuildReport?accessString=f5380d42dc61d279b05f53a424fcf9238f894bd060fb9389e4f1284d21341a28).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-03 21:57 UTC, Jak-MS commented
#assign: @robinharwood, @Xelu86 

Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-01-10 15:00 UTC, robinharwood requested changes
Thanks @gswashington - just a couple of changes.

Thanks,
Robin

2023-01-10 15:00 UTC, robinharwood commented on WindowsServerDocs/administration/windows-commands/cprofile.md
> +description: Reference article for the cprofile command. This command is deprecated and is not guaranteed to be supported in future releases of Windows.
```suggestion
description: Reference article for the cprofile command. The command cprofile is deprecated and maybe removed them from a future releases of Windows.
```

2023-01-10 15:00 UTC, robinharwood commented on WindowsServerDocs/administration/windows-commands/cprofile.md
> +The command cprofile is deprecated and is not guaranteed to be supported in future releases of Windows.
```suggestion
The command cprofile is deprecated and maybe removed them from a future releases of Windows.
```

2023-01-24 12:44 UTC, robinharwood commented
As mentioned, I'm closing this PR down.

2023-01-24 12:44 UTC, closed without merging