Acrolinx quality improvements: auditpol-bitsadmin-cache-and-getlimit.md
MicrosoftDocs/windowsserverdocs pull request #6943
Opened 2023-01-06 22:23 UTC by gswashington

2023-01-06 22:25 UTC, opbld31 commented
Learn Build status updates of commit _[eac13b5](https://github.com/gswashington/windowsserverdocs/commits/eac13b522cc74ab11b9cdd4888a136ffe9cd8194)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/bitsadmin-getproxybypasslist.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-bitsadmin-cache-and-getlimit.md-acrolinx/WindowsServerDocs/administration/windows-commands/bitsadmin-getproxybypasslist.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202301062223481368-6943/BuildReport?accessString=d1021f9417d57da95672151ed2d9bfb29fe91d27ee4d4bcf989136a2671be2b7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-06 22:29 UTC, Jak-MS commented
@JasonGerend 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-01-10 12:19 UTC, robinharwood requested changes
Hey @gswashington - could you also look to replace the word _additional_ on line 40, for example, Other references.

Thanks,

Robin

2023-01-26 14:33 UTC, robinharwood approved these changes

2023-01-26 14:36 UTC, merged