Acrolinx quality improvements: bitsadmin-util-and-help.md
MicrosoftDocs/windowsserverdocs pull request #6945
Opened 2023-01-06 22:59 UTC by gswashington

2023-01-06 23:01 UTC, opbld30 commented
Learn Build status updates of commit _[ca8eb51](https://github.com/gswashington/windowsserverdocs/commits/ca8eb51ddecdc80740381b16901028a454113f2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/windows-commands/bitsadmin-util-and-help.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-bitsadmin-util-and-help.md.acrolinx3/WindowsServerDocs/administration/windows-commands/bitsadmin-util-and-help.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202301062259461669-6945/BuildReport?accessString=cfd8e3f3fce7b8985acf950947a0893c630e2dace3c101d5505611381a2fac31).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-09 21:30 UTC, Jak-MS commented
#assign: @robinharwood, @Xelu86 

Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-01-10 12:24 UTC, robinharwood requested changes
Hi @gswashington,

You change line 24 to provide easier to read introductory line?  Could you also look to replace the word additional on line 30, for example, Other references.

Thanks,

Robin

2023-01-26 14:45 UTC, robinharwood commented
@gswashington - A couple of minor changes. Merging now.

2023-01-26 14:45 UTC, robinharwood approved these changes

2023-01-26 14:46 UTC, merged