Acrolinx quality improvements: slb-gateway-performance.md
MicrosoftDocs/windowsserverdocs pull request #6973
Opened 2023-01-17 23:09 UTC by gswashington

2023-01-17 23:11 UTC, opbld33 commented
Learn Build status updates of commit _[fc0c187](https://github.com/gswashington/windowsserverdocs/commits/fc0c1874f98fb4faa702da11c9e5cb791da294a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WindowsServerDocs/administration/performance-tuning/subsystem/software-defined-networking/slb-gateway-performance.md](https://github.com/gswashington/windowsserverdocs/blob/gsoler-slb-gateway-performance.md-acrolinx/WindowsServerDocs/administration/performance-tuning/subsystem/software-defined-networking/slb-gateway-performance.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/dfd377af-29c7-a16c-d5b9-1896710742b3/202301172309410832-6973/BuildReport?accessString=bafb1903d7acb4912874385ab055738cec2d84d14f4067a247c6b221a12fc8a8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/dfd377af-29c7-a16c-d5b9-1896710742b3?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-18 15:57 UTC, Court72 commented
@robinharwood, @Xelu86

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-01-19 14:11 UTC, robinharwood requested changes
Hey @gswashington, just a few complex sentences to simplify.

Thanks,
Robin

2023-01-19 14:11 UTC, robinharwood commented on WindowsServerDocs/administration/performance-tuning/subsystem/software-defined-networking/slb-gateway-performance.md
> +No additional performance tuning is required to configure the Network Controller or the Hyper-V host for load balancing beyond what is described in the [Software Defined Networking](index.md) section
Both these sentences are quite complex. Could they be simplified?

2023-01-19 14:11 UTC, robinharwood commented on WindowsServerDocs/administration/performance-tuning/subsystem/software-defined-networking/slb-gateway-performance.md
> +In some cases, when the source of the request originates from an SDN host that is added to the same Network Controller that manages the VIP, further optimization of the inbound path for the request i
Still quite complex, could it be split up or simplified?

2023-01-19 14:11 UTC, robinharwood commented on WindowsServerDocs/administration/performance-tuning/subsystem/software-defined-networking/slb-gateway-performance.md
>  Each SLB Mux VM must be sized according to the guidelines provided in the SDN infrastructure virtual machine role requirements section of the  [Plan a Software Defined Network Infrastructure](/azure-
Also quite complex. Could it be simplified?

2023-01-27 15:47 UTC, robinharwood commented
@gswashington, a few updates but looks good. Merging now.

2023-01-27 15:48 UTC, merged