gsoler3 Acrolinx quality push: ad-forest-recovery-nonauthoritative-re…
MicrosoftDocs/windowsserverdocs pull request #7167
Opened 2023-03-29 21:53 UTC by gswashington

…store.md

2023-03-30 16:47 UTC, ShannonLeavitt commented
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-05-03 10:05 UTC, robinharwood requested changes

2023-05-03 10:05 UTC, robinharwood commented on WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Nonauthoritative-Restore.md
> +The following procedures use the Wbadmin.exe to perform a nonauthoritative restore of Active Directory or Active Directory Domain Services (AD DS). If you're using a different backup solution or if y
Could you make this less complex?

> If you're using a different backup solution or if you intend to complete the authoritative restore of SYSVOL later in the forest recovery process, you can perform an authoritative restore of SYSVOL by using these alternative methods:

2023-05-03 10:05 UTC, robinharwood commented on WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Nonauthoritative-Restore.md
> +- If you're using File Replication Service (FRS) to replicate SYSVOL, follow the steps in [article 290762](/troubleshoot/windows-server/networking/use-burflags-to-reinitialize-frs) in the Microsoft K
Could you replace the passive voice here?

>To determine if SYSVOL **is replicated by** FRS, see [Determining Whether a Domain Controller's SYSVOL Folder is Replicated by DFSR or FRS]

2023-05-03 10:05 UTC, robinharwood commented on WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Nonauthoritative-Restore.md
>  - If you are using Distributed File System (DFS) Replication to replicate SYSVOL, see [Perform an authoritative synchronization of DFSR-replicated SYSVOL](AD-Forest-Recovery-Authoritative-Recovery-SY
```suggestion
- If you're using Distributed File System (DFS) Replication to replicate SYSVOL, see [Perform an authoritative synchronization of DFSR-replicated SYSVOL](AD-Forest-Recovery-Authoritative-Recovery-SYSVOL.md).

```

2023-05-03 10:05 UTC, robinharwood commented on WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Nonauthoritative-Restore.md
> +Use the following procedure to perform a nonauthoritative restore of AD DS and an authoritative restore of SYSVOL at the same time by using wbadmin.exe on a DC that runs Windows Server 2012, Windows
Could you make this less complex?

> Use the following procedure to perform a nonauthoritative restore of AD DS and an authoritative restore of SYSVOL at the same time by using wbadmin.exe on a DC that runs Windows Server 2012, Windows Server 2008 R2, or Windows Server 2008.

2023-05-19 17:44 UTC, robinharwood commented
Closing due to duplicated changes.

2023-05-19 17:44 UTC, closed without merging